name: Parallel Cypress Tests
on: [push]
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest # Actualizado a Node.js 16
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: npm i
      - name: Cypress run
        run: npx cypress run --browser chrome