name: Parallel Cypress Tests
on: [push]
permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: Cypress run
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: npm i
      - name: Cypress run
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}