name: Parallel Cypress Tests
on: [push]
permissions:
  contents: write
  pull-requests: write
jobs:
  test:
    name: Cypress run on ${{ matrix.browser }}
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: npm i
      - name: Cypress run
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser ${{ matrix.browser }} --parallel
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}